# Generated by Django 5.0.6 on 2024-05-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_date',
        ),
    ]
